elements:
  ## เมื่อธาตุอื่นๆ มาตีธาตุไฟ
  # FIRE:
      ## ธาตุเหล่านี้ชนะทางธาตุไฟ ทำดาเมจเเรงขึ้น
      # WATER: 0.4
      # DARKNESS: 0.2
      # LIGHTNESS: 0.2
      ## ธาตุเหล่านี้แพ้ทางธาตุไฟ ทำดาเมจเบาลง
      # ICE: -0.4